pipelines:
  seondpipeline:
    group: HelloworldGroup
    materials:
      HelloMaterial:
        git: https://github.com/Unlockwork/hello.git
        branch: master
    stages:
     - publish:
          jobs:
            run:
              tasks:
                - exec:
                   command: bash
                   arguments:
                    - -c
                    - ant run
